server:
  port: 9898

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.41.26:3306/gs_r1?serverTimezone=UTC
    username: root
    password: newpassword
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
